CREATE TABLE IF NOT EXISTS TB_USER(
    id UUID PRIMARY KEY UNIQUE NOT NULL,
    cpf CHAR(11) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(50) NOT NULL,
    street VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    role VARCHAR(20) NOT NULL
);